add print icon
anarock/pebble pull request #380
Opened 2021-03-10 17:36 UTC by appy9

2021-03-14 16:57 UTC, zhirzh requested changes

2021-03-14 16:57 UTC, zhirzh commented on packages/pebble-shared/svgs/print.svg
> +<?xml version="1.0" encoding="utf-8"?>
pebble icons should be 1000x1000 with no space btw in horizontal direction (left/right edges)

2021-03-14 17:20 UTC, zhirzh approved these changes

2021-03-15 09:44 UTC, ChaitanyaGadodia commented
@appy9 I hope the svg is optimized, if not: `https://jakearchibald.github.io/svgomg/`. Let me know if good to go.

2021-03-15 09:55 UTC, appy9 commented
> @appy9 I hope the svg is optimized, if not: `https://jakearchibald.github.io/svgomg/`. Let me know if good to go.

@ChaitanyaGadodia yes thanks, I optimised it further now.

2021-03-15 10:50 UTC, zhirzh approved these changes

2021-03-15 12:27 UTC, ChaitanyaGadodia approved these changes

2021-03-15 12:27 UTC, merged