error message prop for dateInput
anarock/pebble pull request #428
Opened 2023-02-16 15:44 UTC by venky-0710

2023-02-16 16:55 UTC, zhirzh requested changes

2023-02-16 16:55 UTC, zhirzh commented on packages/pebble-web/src/components/styles/Date.styles.ts
> +  borderRadius: "0px 0px 3px 3px",
calendar component shouldn't have border radius

2023-02-16 16:55 UTC, zhirzh commented on packages/pebble-web/src/components/styles/Date.styles.ts
> +  fontWeight: 500,
check `messageStyle` typography in `Input.styles.ts`

2023-02-16 16:55 UTC, zhirzh commented on packages/pebble-web/src/components/styles/Date.styles.ts
> +  display: "flex",
no need for flex. `errorMessage` div only contains text

2023-02-16 16:55 UTC, zhirzh commented on packages/pebble-web/src/components/styles/Date.styles.ts
> +  padding: "11px"
adjust padding to left-align error message with calendar dates

2023-02-17 12:14 UTC, SiriusV21 approved these changes

2023-02-22 10:04 UTC, appy9 approved these changes

2023-02-22 10:05 UTC, zhirzh approved these changes

2023-02-22 10:05 UTC, merged